# Используем Node для разработки
FROM node:20-alpine

WORKDIR /app

# Устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем код
COPY . .

# Открываем порт, на котором работает Vite
EXPOSE 5173

# Запускаем Vite dev сервер
CMD ["npm", "run", "dev", "--", "--host"]
